# Generated by Django 3.1.5 on 2021-01-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='it_news',
            fields=[
                ('title', models.CharField(max_length=100, unique=True)),
                ('time', models.CharField(max_length=100)),
                ('preview', models.TextField(unique=True, verbose_name='preview')),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
            ],
            options={
                'verbose_name': 'it_news_post',
                'verbose_name_plural': 'it_news_posts',
                'db_table': 'it_news_posts',
                'ordering': ('-id',),
            },
        ),
    ]
