# Generated by Django 3.1.5 on 2021-01-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_news',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
