# Generated by Django 3.1.5 on 2021-01-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='today_weather_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real', models.BooleanField(default=True)),
                ('main', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=120)),
            ],
        ),
    ]
