# Generated by Django 3.1.5 on 2021-01-30 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='it_news',
        ),
    ]
